// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTPiJtpa3Y1bEHHYRHnzhhaf64CnB1Og',
    appId: '1:510868151047:web:ffecc54132d053b6a183a2',
    messagingSenderId: '510868151047',
    projectId: 'x-ray-entry',
    authDomain: 'x-ray-entry.firebaseapp.com',
    storageBucket: 'x-ray-entry.firebasestorage.app',
    measurementId: 'G-CCGGN5BFQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1TFP26VVCRW7cjtWqBwX0FAllPZMz9hI',
    appId: '1:510868151047:android:04715ad9b5c8a421a183a2',
    messagingSenderId: '510868151047',
    projectId: 'x-ray-entry',
    storageBucket: 'x-ray-entry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaD_FMoMfSR-SVONqWxu65Vk0VTW1_Gvg',
    appId: '1:510868151047:ios:ae365cda72bd06d8a183a2',
    messagingSenderId: '510868151047',
    projectId: 'x-ray-entry',
    storageBucket: 'x-ray-entry.firebasestorage.app',
    iosBundleId: 'com.example.xRayEntryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaD_FMoMfSR-SVONqWxu65Vk0VTW1_Gvg',
    appId: '1:510868151047:ios:ae365cda72bd06d8a183a2',
    messagingSenderId: '510868151047',
    projectId: 'x-ray-entry',
    storageBucket: 'x-ray-entry.firebasestorage.app',
    iosBundleId: 'com.example.xRayEntryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYTPiJtpa3Y1bEHHYRHnzhhaf64CnB1Og',
    appId: '1:510868151047:web:bfd0804b44fe5b33a183a2',
    messagingSenderId: '510868151047',
    projectId: 'x-ray-entry',
    authDomain: 'x-ray-entry.firebaseapp.com',
    storageBucket: 'x-ray-entry.firebasestorage.app',
    measurementId: 'G-9M2D926M4N',
  );
}
